on:
  push:
    branches-ignore: [main]
  workflow_dispatch:
  workflow_call:

name: build
jobs:
  flatpak:
    name: build flatpak
    runs-on: self-hosted
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    strategy:
      matrix:
        # arch: [x86_64, aarch64]
        arch: [x86_64]
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: lark.flatpak
          manifest-path: com.larksuite.Lark.yaml
          arch: ${{ matrix.arch }}
          upload-artifact: true


  build2:
    strategy:
      matrix:
        # arch: [x86_64, aarch64]
        arch: [x86_64]
    needs: flatpak
    runs-on: self-hosted
    steps:
    - name: download artifacts
      uses: actions/download-artifact@v4
      with:
        name: lark-${{ matrix.arch }}
        path: lark-${{ matrix.arch }}.flatpak
