on:
  push:
    branches-ignore: [main]
  workflow_dispatch:
  workflow_call:

name: build
jobs:
  flatpak:
    name: build flatpak
    runs-on: self-hosted
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: lark.flatpak
          manifest-path: com.larksuite.Lark.yaml
          arch: ${{ matrix.arch }}
          cache-key: flatpak-builder-${{ github.ref_name }}
          upload-artifact: true