on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

name: release
jobs:
  build:
    uses: ritzk/com.larksuite.Lark/.github/workflows/build.yml@main

  release:
    strategy:
      matrix:
        arch: [x86_64, aarch64] 
    needs: build
    runs-on: self-hosted
    steps:
    - name: download artifacts
      uses: actions/download-artifact@v4
      with:
        name: lark-${{ matrix.arch }}
        path: lark-${{ matrix.arch }}.flatpak
    - uses: ncipollo/release-action@v1
      with:
        artifacts: lark-${{ matrix.arch }}.flatpak
